### ISSUE TITLE
Plugins using the Splatoon API are incompatible with Splatoon installed from this repo

### ISSUE THREAD

**Issue by ghost** [Akurosia/MyCustomDalamudPluginRepoCollection#19]
Hi, more to let you know than a real request (I don't use this repo, but [have had someone who's installed Splatoon using this repo](https://github.com/carvelli/PalacePal/issues/3))

With how the Splatoon API is implemented, no plugin can interact with the Splatoon distributed here. Besides my own plugin, the other plugin I know uses the API is AbyssosToolbox - which is also in your repo, clicking `Test splatoon connection` likewise doesn't work.

```
[ERR] [ECommons] [AbyssosToolbox] Object reference not set to an instance of an object.
   at System.Object.GetType()
   at ECommons.SplatoonAPI.Element..ctor(ElementType type) in C:\VS\ECommons\ECommons\SplatoonAPI\Element.cs:line 18
   at AbyssosToolbox.AbyssosToolbox.CreateElement(Vector2 x, Single z) in C:\VS\AbyssosToolbox\AbyssosToolbox\AbyssosToolbox.cs:line 129
   at AbyssosToolbox.Gui.DrawTabSettings() in C:\VS\AbyssosToolbox\AbyssosToolbox\Gui.cs:line 79
   at ECommons.ImGuiMethods.ImGuiEx.EzTabBar(String id, ValueTuple`4[] tabs) in C:\VS\ECommons\ECommons\ImGuiMethods\ImGuiEx.cs:line 305
   at AbyssosToolbox.Gui.Draw() in C:\VS\AbyssosToolbox\AbyssosToolbox\Gui.cs:line 20
   at ECommons.GenericHelpers.Safe(Action a, Boolean suppressErrors) in C:\VS\ECommons\ECommons\GenericHelpers.cs:line 309
```

Oh, and you also have Splatoon included twice in your repository (one version is outdated, as it still points to https://github.com/Eternita-S/

**Comment by Akurosia** [comment]
i have removed the old entry from Eternita-S can you confirm the version of the plugin installed is 2.2.0.2 ?

**Comment by ghost** [comment]
Looks like it:

![grafik](https://user-images.githubusercontent.com/24593801/200342601-603539c6-cf3f-44d1-8a9d-0bb2dee59346.png)

**Comment by Akurosia** [comment]
i dont know exactly why it error, but somehow its referncing only the name "Splatoon" and as soon it is not Splatoon it throws an error

**Comment by Akurosia** [comment]
Should be fixed now, you may need to remove and reinstall splatoon (which now is only called Splatoon and not Splatoon [Aku Api 7] )

**Comment by ghost** [comment]
Looks like it's working now.
